server:
  address: 0.0.0.0
  port: ${PORT:8080}  # Dynamic port for Koyeb

spring:
  application:
    name: webpage-ai-rag
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ragdb}
    username: ${DATABASE_USER:raguser}
    password: ${DATABASE_PASSWORD:ragpassword}
    hikari:
      connection-timeout: 10000  # Higher timeout for cloud
  ai:
    ollama:
      chat:
        url: ${OLLAMA_URL:http://localhost:11434}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true